/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.27
 * Generated at: 2023-06-22 08:40:52 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class menu_002dpage_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(6);
    _jspx_dependants.put("/WEB-INF/include-nav.jsp", Long.valueOf(1681738997229L));
    _jspx_dependants.put("/WEB-INF/modal-menu-add.jsp", Long.valueOf(1686832846848L));
    _jspx_dependants.put("/WEB-INF/modal-menu-edit.jsp", Long.valueOf(1686832846865L));
    _jspx_dependants.put("/WEB-INF/include-head.jsp", Long.valueOf(1681738997227L));
    _jspx_dependants.put("/WEB-INF/include-sidebar.jsp", Long.valueOf(1686746201386L));
    _jspx_dependants.put("/WEB-INF/modal-menu-confirm.jsp", Long.valueOf(1686832846858L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"zh-CN\">\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("<meta name=\"description\" content=\"\">\r\n");
      out.write("<meta name=\"author\" content=\"\">\r\n");
      out.write("<base\r\n");
      out.write("\thref=\"http://");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.serverName }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(':');
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.serverPort }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/\" />\r\n");
      out.write("<link rel=\"stylesheet\" href=\"bootstrap/css/bootstrap.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/font-awesome.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/main.css\">\r\n");
      out.write("<style>\r\n");
      out.write(".tree li {\r\n");
      out.write("\tlist-style-type: none;\r\n");
      out.write("\tcursor: pointer;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".tree-closed {\r\n");
      out.write("\theight: 40px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".tree-expanded {\r\n");
      out.write("\theight: auto;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("<script type=\"text/javascript\" src=\"jquery/jquery-2.1.1.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"bootstrap/js/bootstrap.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"script/docs.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"layer/layer.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\t$(function() {\r\n");
      out.write("\t\t$(\".list-group-item\").click(function() {\r\n");
      out.write("\t\t\tif ($(this).find(\"ul\")) {\r\n");
      out.write("\t\t\t\t$(this).toggleClass(\"tree-closed\");\r\n");
      out.write("\t\t\t\tif ($(this).hasClass(\"tree-closed\")) {\r\n");
      out.write("\t\t\t\t\t$(\"ul\", this).hide(\"fast\");\r\n");
      out.write("\t\t\t\t} else {\r\n");
      out.write("\t\t\t\t\t$(\"ul\", this).show(\"fast\");\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\t});\r\n");
      out.write("</script>\r\n");
      out.write("<title>尚筹网</title>\r\n");
      out.write("</head>");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" href=\"ztree/zTreeStyle.css\"/>\r\n");
      out.write("<script type=\"text/javascript\" src=\"ztree/jquery.ztree.all-3.5.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"crowd/my-menu.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\r\n");
      out.write("\t$(function(){\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t// 調用專門封裝好的函數初始化樹形結構\r\n");
      out.write("\t\tgenerateTree();\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t// 給添加子節點按鈕綁定單擊響應函數\r\n");
      out.write("\t\t$(\"#treeDemo\").on(\"click\",\".addBtn\",function(){\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t// 將當前節點的id，作為新節點的pid保存到全局變量\r\n");
      out.write("\t\t\twindow.pid = this.id;\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t// 打開模態框\r\n");
      out.write("\t\t\t$(\"#menuAddModal\").modal(\"show\");\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t// 給添加子節點的模態框中的保存按鈕綁定單擊響應函數\r\n");
      out.write("\t\t$(\"#menuSaveBtn\").click(function(){\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t// 收集表單項中用戶輸入的數據\r\n");
      out.write("\t\t\tvar name = $.trim($(\"#menuAddModal [name=name]\").val());\r\n");
      out.write("\t\t\tvar url = $.trim($(\"#menuAddModal [name=url]\").val());\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t// 單選按鈕要定位到“被選中”的那一個\r\n");
      out.write("\t\t\tvar icon = $(\"#menuAddModal [name=icon]:checked\").val();\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t// 發送Ajax請求\r\n");
      out.write("\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\t\"url\":\"menu/save.json\",\r\n");
      out.write("\t\t\t\t\"type\":\"post\",\r\n");
      out.write("\t\t\t\t\"data\":{\r\n");
      out.write("\t\t\t\t\t\"pid\": window.pid,\r\n");
      out.write("\t\t\t\t\t\"name\":name,\r\n");
      out.write("\t\t\t\t\t\"url\":url,\r\n");
      out.write("\t\t\t\t\t\"icon\":icon\r\n");
      out.write("\t\t\t\t},\r\n");
      out.write("\t\t\t\t\"dataType\":\"json\",\r\n");
      out.write("\t\t\t\t\"success\":function(response){\r\n");
      out.write("\t\t\t\t\tvar result = response.result;\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\tif(result == \"SUCCESS\") {\r\n");
      out.write("\t\t\t\t\t\tlayer.msg(\"操作成功！\");\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t// 重新加載樹形結構，註意：要在確認服務器端完成保存操作後再刷新\r\n");
      out.write("\t\t\t\t\t\t// 否則有可能刷新不到最新的數據，因為這裏是異步的\r\n");
      out.write("\t\t\t\t\t\tgenerateTree();\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\tif(result == \"FAILED\") {\r\n");
      out.write("\t\t\t\t\t\tlayer.msg(\"操作失敗！\"+response.message);\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t},\r\n");
      out.write("\t\t\t\t\"error\":function(response){\r\n");
      out.write("\t\t\t\t\tlayer.msg(response.status+\" \"+response.statusText);\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t// 關閉模態框\r\n");
      out.write("\t\t\t$(\"#menuAddModal\").modal(\"hide\");\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t// 清空表單\r\n");
      out.write("\t\t\t// jQuery對象調用click()函數，裏面不傳任何參數，相當於用戶點擊了一下\r\n");
      out.write("\t\t\t$(\"#menuResetBtn\").click();\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t// 給編輯按鈕綁定單擊響應函數\r\n");
      out.write("\t\t$(\"#treeDemo\").on(\"click\",\".editBtn\",function(){\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t// 將當前節點的id保存到全局變量\r\n");
      out.write("\t\t\twindow.id = this.id;\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t// 打開模態框\r\n");
      out.write("\t\t\t$(\"#menuEditModal\").modal(\"show\");\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\t// 獲取zTreeObj對象\r\n");
      out.write("\t\t\tvar zTreeObj = $.fn.zTree.getZTreeObj(\"treeDemo\");\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t// 根據id屬性查詢節點對象\r\n");
      out.write("\t\t\t// 用來搜索節點的屬性名\r\n");
      out.write("\t\t\tvar key = \"id\";\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t// 用來搜索節點的屬性值\r\n");
      out.write("\t\t\tvar value = window.id;\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tvar currentNode = zTreeObj.getNodeByParam(key, value);\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t// 回顯表單數據\r\n");
      out.write("\t\t\t$(\"#menuEditModal [name=name]\").val(currentNode.name);\r\n");
      out.write("\t\t\t$(\"#menuEditModal [name=url]\").val(currentNode.url);\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t// 回顯radio可以這樣理解：被選中的radio的value屬性可以組成一個數組，\r\n");
      out.write("\t\t\t// 然後再用這個數組設置回radio，就能夠把對應的值選中\r\n");
      out.write("\t\t\t$(\"#menuEditModal [name=icon]\").val([currentNode.icon]);\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t// 給更新模態框中的更新按鈕綁定單擊響應函數\r\n");
      out.write("\t\t$(\"#menuEditBtn\").click(function(){\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t// 收集表單數據\r\n");
      out.write("\t\t\tvar name = $(\"#menuEditModal [name=name]\").val();\r\n");
      out.write("\t\t\tvar url = $(\"#menuEditModal [name=url]\").val();\r\n");
      out.write("\t\t\tvar icon = $(\"#menuEditModal [name=icon]:checked\").val();\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t// 發送Ajax請求\r\n");
      out.write("\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\t\"url\":\"menu/update.json\",\r\n");
      out.write("\t\t\t\t\"type\":\"post\",\r\n");
      out.write("\t\t\t\t\"data\":{\r\n");
      out.write("\t\t\t\t\t\"id\": window.id,\r\n");
      out.write("\t\t\t\t\t\"name\":name,\r\n");
      out.write("\t\t\t\t\t\"url\":url,\r\n");
      out.write("\t\t\t\t\t\"icon\":icon\r\n");
      out.write("\t\t\t\t},\r\n");
      out.write("\t\t\t\t\"dataType\":\"json\",\r\n");
      out.write("\t\t\t\t\"success\":function(response){\r\n");
      out.write("\t\t\t\t\tvar result = response.result;\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\tif(result == \"SUCCESS\") {\r\n");
      out.write("\t\t\t\t\t\tlayer.msg(\"操作成功！\");\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t// 重新加載樹形結構，註意：要在確認服務器端完成保存操作後再刷新\r\n");
      out.write("\t\t\t\t\t\t// 否則有可能刷新不到最新的數據，因為這裏是異步的\r\n");
      out.write("\t\t\t\t\t\tgenerateTree();\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\tif(result == \"FAILED\") {\r\n");
      out.write("\t\t\t\t\t\tlayer.msg(\"操作失敗！\"+response.message);\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t},\r\n");
      out.write("\t\t\t\t\"error\":function(response){\r\n");
      out.write("\t\t\t\t\tlayer.msg(response.status+\" \"+response.statusText);\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t// 關閉模態框\r\n");
      out.write("\t\t\t$(\"#menuEditModal\").modal(\"hide\");\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t// 給“×”按鈕綁定單擊響應函數\r\n");
      out.write("\t\t$(\"#treeDemo\").on(\"click\",\".removeBtn\",function(){\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t// 將當前節點的id保存到全局變量\r\n");
      out.write("\t\t\twindow.id = this.id;\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t// 打開模態框\r\n");
      out.write("\t\t\t$(\"#menuConfirmModal\").modal(\"show\");\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\t// 獲取zTreeObj對象\r\n");
      out.write("\t\t\tvar zTreeObj = $.fn.zTree.getZTreeObj(\"treeDemo\");\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t// 根據id屬性查詢節點對象\r\n");
      out.write("\t\t\t// 用來搜索節點的屬性名\r\n");
      out.write("\t\t\tvar key = \"id\";\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t// 用來搜索節點的屬性值\r\n");
      out.write("\t\t\tvar value = window.id;\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tvar currentNode = zTreeObj.getNodeByParam(key, value);\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t$(\"#removeNodeSpan\").html(\"【<i class='\"+currentNode.icon+\"'></i>\"+currentNode.name+\"】\");\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t// 給確認模態框中的OK按鈕綁定單擊響應函數\r\n");
      out.write("\t\t$(\"#confirmBtn\").click(function(){\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\t\"url\":\"menu/remove.json\",\r\n");
      out.write("\t\t\t\t\"type\":\"post\",\r\n");
      out.write("\t\t\t\t\"data\":{\r\n");
      out.write("\t\t\t\t\t\"id\":window.id\r\n");
      out.write("\t\t\t\t},\r\n");
      out.write("\t\t\t\t\"dataType\":\"json\",\r\n");
      out.write("\t\t\t\t\"success\":function(response){\r\n");
      out.write("\t\t\t\t\tvar result = response.result;\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\tif(result == \"SUCCESS\") {\r\n");
      out.write("\t\t\t\t\t\tlayer.msg(\"操作成功！\");\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t// 重新加載樹形結構，註意：要在確認服務器端完成保存操作後再刷新\r\n");
      out.write("\t\t\t\t\t\t// 否則有可能刷新不到最新的數據，因為這裏是異步的\r\n");
      out.write("\t\t\t\t\t\tgenerateTree();\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\tif(result == \"FAILED\") {\r\n");
      out.write("\t\t\t\t\t\tlayer.msg(\"操作失敗！\"+response.message);\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t},\r\n");
      out.write("\t\t\t\t\"error\":function(response){\r\n");
      out.write("\t\t\t\t\tlayer.msg(response.status+\" \"+response.statusText);\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t// 關閉模態框\r\n");
      out.write("\t\t\t$(\"#menuConfirmModal\").modal(\"hide\");\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t\r\n");
      out.write("\t});\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\t");
      out.write("\r\n");
      out.write("<nav class=\"navbar navbar-inverse navbar-fixed-top\" role=\"navigation\">\r\n");
      out.write("\t<div class=\"container-fluid\">\r\n");
      out.write("\t\t<div class=\"navbar-header\">\r\n");
      out.write("\t\t\t<div>\r\n");
      out.write("\t\t\t\t<a class=\"navbar-brand\" style=\"font-size: 32px;\" href=\"#\">众筹平台 -\r\n");
      out.write("\t\t\t\t\t控制面板</a>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div id=\"navbar\" class=\"navbar-collapse collapse\">\r\n");
      out.write("\t\t\t<ul class=\"nav navbar-nav navbar-right\">\r\n");
      out.write("\t\t\t\t<li style=\"padding-top: 8px;\">\r\n");
      out.write("\t\t\t\t\t<div class=\"btn-group\">\r\n");
      out.write("\t\t\t\t\t\t<button type=\"button\"\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"btn btn-default btn-success dropdown-toggle\"\r\n");
      out.write("\t\t\t\t\t\t\tdata-toggle=\"dropdown\">\r\n");
      out.write("\t\t\t\t\t\t\t<i class=\"glyphicon glyphicon-user\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.loginAdmin.userName }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(" <span class=\"caret\"></span>\r\n");
      out.write("\t\t\t\t\t\t</button>\r\n");
      out.write("\t\t\t\t\t\t<ul class=\"dropdown-menu\" role=\"menu\">\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"#\"><i class=\"glyphicon glyphicon-cog\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t个人设置</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"#\"><i class=\"glyphicon glyphicon-comment\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t消息</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li class=\"divider\"></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"admin/do/logout.html\"><i\r\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"glyphicon glyphicon-off\"></i> 退出系统</a></li>\r\n");
      out.write("\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t<li style=\"margin-left: 10px; padding-top: 8px;\">\r\n");
      out.write("\t\t\t\t\t<button type=\"button\" class=\"btn btn-default btn-danger\">\r\n");
      out.write("\t\t\t\t\t\t<span class=\"glyphicon glyphicon-question-sign\"></span> 帮助\r\n");
      out.write("\t\t\t\t\t</button>\r\n");
      out.write("\t\t\t\t</li>\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\t\t\t<form class=\"navbar-form navbar-right\">\r\n");
      out.write("\t\t\t\t<input type=\"text\" class=\"form-control\" placeholder=\"查询\">\r\n");
      out.write("\t\t\t</form>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("</nav>");
      out.write("\r\n");
      out.write("\t<div class=\"container-fluid\">\r\n");
      out.write("\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t");
      out.write("\r\n");
      out.write("<div class=\"col-sm-3 col-md-2 sidebar\">\r\n");
      out.write("\t<div class=\"tree\">\r\n");
      out.write("\t\t<ul style=\"padding-left: 0px;\" class=\"list-group\">\r\n");
      out.write("\t\t\t<li class=\"list-group-item tree-closed\"><a href=\"main.html\"><i\r\n");
      out.write("\t\t\t\t\tclass=\"glyphicon glyphicon-dashboard\"></i> 控制面板</a></li>\r\n");
      out.write("\t\t\t<li class=\"list-group-item tree-closed\"><span><i\r\n");
      out.write("\t\t\t\t\tclass=\"glyphicon glyphicon glyphicon-tasks\"></i> 權限管理 <span\r\n");
      out.write("\t\t\t\t\tclass=\"badge\" style=\"float: right\">3</span></span>\r\n");
      out.write("\t\t\t\t<ul style=\"margin-top: 10px; display: none;\">\r\n");
      out.write("\t\t\t\t\t<li style=\"height: 30px;\"><a href=\"admin/get/page.html\"><i\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"glyphicon glyphicon-user\"></i> 用戶維護</a></li>\r\n");
      out.write("\t\t\t\t\t<li style=\"height: 30px;\"><a href=\"role/to/page.html\"><i\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"glyphicon glyphicon-king\"></i> 角色維護</a></li>\r\n");
      out.write("\t\t\t\t\t<li style=\"height: 30px;\"><a href=\"menu/to/page.html\"><i\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"glyphicon glyphicon-lock\"></i> 菜單維護</a></li>\r\n");
      out.write("\t\t\t\t</ul></li>\r\n");
      out.write("\t\t\t<li class=\"list-group-item tree-closed\"><span><i\r\n");
      out.write("\t\t\t\t\tclass=\"glyphicon glyphicon-ok\"></i> 業務審核 <span class=\"badge\"\r\n");
      out.write("\t\t\t\t\tstyle=\"float: right\">3</span></span>\r\n");
      out.write("\t\t\t\t<ul style=\"margin-top: 10px; display: none;\">\r\n");
      out.write("\t\t\t\t\t<li style=\"height: 30px;\"><a href=\"auth_cert.html\"><i\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"glyphicon glyphicon-check\"></i> 實名認證審核</a></li>\r\n");
      out.write("\t\t\t\t\t<li style=\"height: 30px;\"><a href=\"auth_adv.html\"><i\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"glyphicon glyphicon-check\"></i> 廣告審核</a></li>\r\n");
      out.write("\t\t\t\t\t<li style=\"height: 30px;\"><a href=\"auth_project.html\"><i\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"glyphicon glyphicon-check\"></i> 項目審核</a></li>\r\n");
      out.write("\t\t\t\t</ul></li>\r\n");
      out.write("\t\t\t<li class=\"list-group-item tree-closed\"><span><i\r\n");
      out.write("\t\t\t\t\tclass=\"glyphicon glyphicon-th-large\"></i> 業務管理 <span class=\"badge\"\r\n");
      out.write("\t\t\t\t\tstyle=\"float: right\">7</span></span>\r\n");
      out.write("\t\t\t\t<ul style=\"margin-top: 10px; display: none;\">\r\n");
      out.write("\t\t\t\t\t<li style=\"height: 30px;\"><a href=\"cert.html\"><i\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"glyphicon glyphicon-picture\"></i> 資質維護</a></li>\r\n");
      out.write("\t\t\t\t\t<li style=\"height: 30px;\"><a href=\"type.html\"><i\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"glyphicon glyphicon-equalizer\"></i> 分類管理</a></li>\r\n");
      out.write("\t\t\t\t\t<li style=\"height: 30px;\"><a href=\"process.html\"><i\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"glyphicon glyphicon-random\"></i> 流程管理</a></li>\r\n");
      out.write("\t\t\t\t\t<li style=\"height: 30px;\"><a href=\"advertisement.html\"><i\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"glyphicon glyphicon-hdd\"></i> 廣告管理</a></li>\r\n");
      out.write("\t\t\t\t\t<li style=\"height: 30px;\"><a href=\"message.html\"><i\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"glyphicon glyphicon-comment\"></i> 消息模板</a></li>\r\n");
      out.write("\t\t\t\t\t<li style=\"height: 30px;\"><a href=\"project_type.html\"><i\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"glyphicon glyphicon-list\"></i> 項目分類</a></li>\r\n");
      out.write("\t\t\t\t\t<li style=\"height: 30px;\"><a href=\"tag.html\"><i\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"glyphicon glyphicon-tags\"></i> 項目標簽</a></li>\r\n");
      out.write("\t\t\t\t</ul></li>\r\n");
      out.write("\t\t\t<li class=\"list-group-item tree-closed\"><a href=\"param.html\"><i\r\n");
      out.write("\t\t\t\t\tclass=\"glyphicon glyphicon-list-alt\"></i> 參數管理</a></li>\r\n");
      out.write("\t\t</ul>\r\n");
      out.write("\t</div>\r\n");
      out.write("</div>");
      out.write("\r\n");
      out.write("\t\t\t<div class=\"col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<div class=\"panel panel-default\">\r\n");
      out.write("\t\t\t\t\t<div class=\"panel-heading\">\r\n");
      out.write("\t\t\t\t\t\t<i class=\"glyphicon glyphicon-th-list\"></i> 權限菜單列表\r\n");
      out.write("\t\t\t\t\t\t<div style=\"float: right; cursor: pointer;\" data-toggle=\"modal\"\r\n");
      out.write("\t\t\t\t\t\t\tdata-target=\"#myModal\">\r\n");
      out.write("\t\t\t\t\t\t\t<i class=\"glyphicon glyphicon-question-sign\"></i>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"panel-body\">\r\n");
      out.write("\t\t\t\t\t\t<!-- 這個ul標簽是zTree動態生成的節點所依附的靜態節點 -->\r\n");
      out.write("\t\t\t\t\t\t<ul id=\"treeDemo\" class=\"ztree\"></ul>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t");
      out.write("\r\n");
      out.write("<div id=\"menuAddModal\" class=\"modal fade\" tabindex=\"-1\" role=\"dialog\">\r\n");
      out.write("\t<div class=\"modal-dialog\" role=\"document\">\r\n");
      out.write("\t\t<div class=\"modal-content\">\r\n");
      out.write("\t\t\t<div class=\"modal-header\">\r\n");
      out.write("\t\t\t\t<button type=\"button\" class=\"close\" data-dismiss=\"modal\"\r\n");
      out.write("\t\t\t\t\taria-label=\"Close\">\r\n");
      out.write("\t\t\t\t\t<span aria-hidden=\"true\">&times;</span>\r\n");
      out.write("\t\t\t\t</button>\r\n");
      out.write("\t\t\t\t<h4 class=\"modal-title\">尚籌網系統彈窗</h4>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<form>\r\n");
      out.write("\t\t\t\t<div class=\"modal-body\">\r\n");
      out.write("\t\t\t\t\t請輸入節點名稱：<input type=\"text\" name=\"name\" /><br />\r\n");
      out.write("\t\t\t\t\t請輸入URL地址：<input type=\"text\" name=\"url\" /><br />\r\n");
      out.write("\t\t\t\t\t<i class=\"glyphicon glyphicon-th-list\"></i>\r\n");
      out.write("\t\t\t\t\t<input type=\"radio\" name=\"icon\" value=\"glyphicon glyphicon-th-list\" />&nbsp;\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<i class=\"glyphicon glyphicon-dashboard\"></i> \r\n");
      out.write("\t\t\t\t\t<input type=\"radio\" name=\"icon\" value=\"glyphicon glyphicon-dashboard\" /> &nbsp;\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<i class=\"glyphicon glyphicon glyphicon-tasks\"></i> \r\n");
      out.write("\t\t\t\t\t<input type=\"radio\" name=\"icon\" value=\"glyphicon glyphicon glyphicon-tasks\" /> &nbsp;\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<i class=\"glyphicon glyphicon-user\"></i> \r\n");
      out.write("\t\t\t\t\t<input type=\"radio\" name=\"icon\" value=\"glyphicon glyphicon-user\" /> &nbsp;\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<i class=\"glyphicon glyphicon-king\"></i> \r\n");
      out.write("\t\t\t\t\t<input type=\"radio\" name=\"icon\" value=\"glyphicon glyphicon-king\" /> &nbsp;\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<i class=\"glyphicon glyphicon-lock\"></i> \r\n");
      out.write("\t\t\t\t\t<input type=\"radio\" name=\"icon\" value=\"glyphicon glyphicon-lock\" /> &nbsp;\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<i class=\"glyphicon glyphicon-ok\"></i> \r\n");
      out.write("\t\t\t\t\t<input type=\"radio\" name=\"icon\" value=\"glyphicon glyphicon-ok\" /> &nbsp;\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<i class=\"glyphicon glyphicon-check\"></i> \r\n");
      out.write("\t\t\t\t\t<input type=\"radio\" name=\"icon\" value=\"glyphicon glyphicon-check\" /> &nbsp;\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<i class=\"glyphicon glyphicon-th-large\"></i>\r\n");
      out.write("\t\t\t\t\t<input type=\"radio\" name=\"icon\" value=\"glyphicon glyphicon-th-large\" /> <br /> \r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<i class=\"glyphicon glyphicon-picture\"></i> \r\n");
      out.write("\t\t\t\t\t<input type=\"radio\" name=\"icon\" value=\"glyphicon glyphicon-picture\" /> &nbsp;\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<i class=\"glyphicon glyphicon-equalizer\"></i> \r\n");
      out.write("\t\t\t\t\t<input type=\"radio\" name=\"icon\" value=\"glyphicon glyphicon-equalizer\" /> &nbsp;\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<i class=\"glyphicon glyphicon-random\"></i> \r\n");
      out.write("\t\t\t\t\t<input type=\"radio\" name=\"icon\" value=\"glyphicon glyphicon-random\" /> &nbsp;\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<i class=\"glyphicon glyphicon-hdd\"></i> \r\n");
      out.write("\t\t\t\t\t<input type=\"radio\" name=\"icon\" value=\"glyphicon glyphicon-hdd\" /> &nbsp;\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<i class=\"glyphicon glyphicon-comment\"></i> \r\n");
      out.write("\t\t\t\t\t<input type=\"radio\" name=\"icon\" value=\"glyphicon glyphicon-comment\" /> &nbsp;\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<i class=\"glyphicon glyphicon-list\"></i> \r\n");
      out.write("\t\t\t\t\t<input type=\"radio\" name=\"icon\" value=\"glyphicon glyphicon-list\" /> &nbsp;\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<i class=\"glyphicon glyphicon-tags\"></i> \r\n");
      out.write("\t\t\t\t\t<input type=\"radio\" name=\"icon\" value=\"glyphicon glyphicon-tags\" /> &nbsp;\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<i class=\"glyphicon glyphicon-list-alt\"></i> \r\n");
      out.write("\t\t\t\t\t<input type=\"radio\" name=\"icon\" value=\"glyphicon glyphicon-list-alt\" /> &nbsp;\r\n");
      out.write("\t\t\t\t\t<br />\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"modal-footer\">\r\n");
      out.write("\t\t\t\t\t<button id=\"menuSaveBtn\" type=\"button\" class=\"btn btn-default\"><i class=\"glyphicon glyphicon-plus\"></i> 保存</button>\r\n");
      out.write("\t\t\t\t\t<button id=\"menuResetBtn\" type=\"reset\" class=\"btn btn-primary\"><i class=\"glyphicon glyphicon-refresh\"></i> 重置</button>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</form>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("</div>");
      out.write('\r');
      out.write('\n');
      out.write('	');
      out.write("\r\n");
      out.write("<div id=\"menuConfirmModal\" class=\"modal fade\" tabindex=\"-1\" role=\"dialog\">\r\n");
      out.write("\t<div class=\"modal-dialog\" role=\"document\">\r\n");
      out.write("\t\t<div class=\"modal-content\">\r\n");
      out.write("\t\t\t<div class=\"modal-header\">\r\n");
      out.write("\t\t\t\t<button type=\"button\" class=\"close\" data-dismiss=\"modal\"\r\n");
      out.write("\t\t\t\t\taria-label=\"Close\">\r\n");
      out.write("\t\t\t\t\t<span aria-hidden=\"true\">&times;</span>\r\n");
      out.write("\t\t\t\t</button>\r\n");
      out.write("\t\t\t\t<h4 class=\"modal-title\">尚籌網系統彈窗</h4>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<form>\r\n");
      out.write("\t\t\t\t<div class=\"modal-body\">\r\n");
      out.write("\t\t\t\t\t您真的要刪除<span id=\"removeNodeSpan\"></span>這個節點嗎？\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"modal-footer\">\r\n");
      out.write("\t\t\t\t\t<button id=\"confirmBtn\" type=\"button\" class=\"btn btn-danger\"><i class=\"glyphicon glyphicon-ok\"></i> OK</button>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</form>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("</div>");
      out.write('\r');
      out.write('\n');
      out.write('	');
      out.write("\r\n");
      out.write("<div id=\"menuEditModal\" class=\"modal fade\" tabindex=\"-1\" role=\"dialog\">\r\n");
      out.write("\t<div class=\"modal-dialog\" role=\"document\">\r\n");
      out.write("\t\t<div class=\"modal-content\">\r\n");
      out.write("\t\t\t<div class=\"modal-header\">\r\n");
      out.write("\t\t\t\t<button type=\"button\" class=\"close\" data-dismiss=\"modal\"\r\n");
      out.write("\t\t\t\t\taria-label=\"Close\">\r\n");
      out.write("\t\t\t\t\t<span aria-hidden=\"true\">&times;</span>\r\n");
      out.write("\t\t\t\t</button>\r\n");
      out.write("\t\t\t\t<h4 class=\"modal-title\">尚籌網系統彈窗</h4>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<form>\r\n");
      out.write("\t\t\t\t<div class=\"modal-body\">\r\n");
      out.write("\t\t\t\t\t請輸入節點名稱：<input type=\"text\" name=\"name\" /><br />\r\n");
      out.write("\t\t\t\t\t請輸入URL地址：<input type=\"text\" name=\"url\" /><br />\r\n");
      out.write("\t\t\t\t\t<i class=\"glyphicon glyphicon-th-list\"></i>\r\n");
      out.write("\t\t\t\t\t<input type=\"radio\" name=\"icon\" value=\"glyphicon glyphicon-th-list\" />&nbsp;\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<i class=\"glyphicon glyphicon-dashboard\"></i> \r\n");
      out.write("\t\t\t\t\t<input type=\"radio\" name=\"icon\" value=\"glyphicon glyphicon-dashboard\" /> &nbsp;\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<i class=\"glyphicon glyphicon glyphicon-tasks\"></i> \r\n");
      out.write("\t\t\t\t\t<input type=\"radio\" name=\"icon\" value=\"glyphicon glyphicon glyphicon-tasks\" /> &nbsp;\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<i class=\"glyphicon glyphicon-user\"></i> \r\n");
      out.write("\t\t\t\t\t<input type=\"radio\" name=\"icon\" value=\"glyphicon glyphicon-user\" /> &nbsp;\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<i class=\"glyphicon glyphicon-king\"></i> \r\n");
      out.write("\t\t\t\t\t<input type=\"radio\" name=\"icon\" value=\"glyphicon glyphicon-king\" /> &nbsp;\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<i class=\"glyphicon glyphicon-lock\"></i> \r\n");
      out.write("\t\t\t\t\t<input type=\"radio\" name=\"icon\" value=\"glyphicon glyphicon-lock\" /> &nbsp;\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<i class=\"glyphicon glyphicon-ok\"></i> \r\n");
      out.write("\t\t\t\t\t<input type=\"radio\" name=\"icon\" value=\"glyphicon glyphicon-ok\" /> &nbsp;\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<i class=\"glyphicon glyphicon-check\"></i> \r\n");
      out.write("\t\t\t\t\t<input type=\"radio\" name=\"icon\" value=\"glyphicon glyphicon-check\" /> &nbsp;\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<i class=\"glyphicon glyphicon-th-large\"></i>\r\n");
      out.write("\t\t\t\t\t<input type=\"radio\" name=\"icon\" value=\"glyphicon glyphicon-th-large\" /> <br /> \r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<i class=\"glyphicon glyphicon-picture\"></i> \r\n");
      out.write("\t\t\t\t\t<input type=\"radio\" name=\"icon\" value=\"glyphicon glyphicon-picture\" /> &nbsp;\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<i class=\"glyphicon glyphicon-equalizer\"></i> \r\n");
      out.write("\t\t\t\t\t<input type=\"radio\" name=\"icon\" value=\"glyphicon glyphicon-equalizer\" /> &nbsp;\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<i class=\"glyphicon glyphicon-random\"></i> \r\n");
      out.write("\t\t\t\t\t<input type=\"radio\" name=\"icon\" value=\"glyphicon glyphicon-random\" /> &nbsp;\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<i class=\"glyphicon glyphicon-hdd\"></i> \r\n");
      out.write("\t\t\t\t\t<input type=\"radio\" name=\"icon\" value=\"glyphicon glyphicon-hdd\" /> &nbsp;\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<i class=\"glyphicon glyphicon-comment\"></i> \r\n");
      out.write("\t\t\t\t\t<input type=\"radio\" name=\"icon\" value=\"glyphicon glyphicon-comment\" /> &nbsp;\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<i class=\"glyphicon glyphicon-list\"></i> \r\n");
      out.write("\t\t\t\t\t<input type=\"radio\" name=\"icon\" value=\"glyphicon glyphicon-list\" /> &nbsp;\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<i class=\"glyphicon glyphicon-tags\"></i> \r\n");
      out.write("\t\t\t\t\t<input type=\"radio\" name=\"icon\" value=\"glyphicon glyphicon-tags\" /> &nbsp;\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<i class=\"glyphicon glyphicon-list-alt\"></i> \r\n");
      out.write("\t\t\t\t\t<input type=\"radio\" name=\"icon\" value=\"glyphicon glyphicon-list-alt\" /> &nbsp;\r\n");
      out.write("\t\t\t\t\t<br />\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"modal-footer\">\r\n");
      out.write("\t\t\t\t\t<button id=\"menuEditBtn\" type=\"button\" class=\"btn btn-default\"><i class=\"glyphicon glyphicon-edit\"></i> 更新</button>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</form>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("</div>");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
